directories:
  output: dist
  buildResources: build
appId: eu.georail.schedule
productName: GeoRail
copyright: GeoRail
files:
  - filter:
      - electron/**/*
      - src/**/*
      - public/**/*
      - server.js
      - config.js
      - package.json
      - '!**/*.map'
      - '!data/**'
      - '!dist/**'
      - '!diagnose-missing-route.js'
asar: true
asarUnpack:
  - public/**
win:
  target:
    - target: nsis
      arch:
        - x64
  icon: build/icon.ico
  artifactName: GeoRail-Setup-${version}.${ext}
nsis:
  oneClick: true
  perMachine: false
  allowToChangeInstallationDirectory: false
  createDesktopShortcut: true
  createStartMenuShortcut: true
  shortcutName: GeoRail
  runAfterFinish: true
linux:
  target:
    - AppImage
  icon: build/icon.png
  category: Utility
  artifactName: GeoRail-${version}.${ext}
mac:
  target:
    - dmg
  icon: build/icon.png
  category: public.app-category.utilities
  artifactName: GeoRail-${version}.${ext}
publish:
  - provider: github
    owner: Chupsman
    repo: MTR-Schedule-manager
electronVersion: 31.7.7
